### ISSUE TITLE
This indicator in a cell

### ISSUE THREAD

**Issue by Ahmedshubber** [Tueno/MaterialLoadingIndicator#2]
@Tueno @sg-ueno  I'm trying to add this indicator in a cell because my images are lagging from the server and I need a placeholder animation like a loading indicator to show the user that there loading in the table. But I added your animation into my image view of my table view cell like this. 

 private var indicator = MaterialLoadingIndicator(frame: CGRect(x: 0, y: 0, width: 50, height: 50))

cell?.imageView.addSubview(indicator)
            indicator.startAnimating()

And I can't see the animation. Can you please help me

**Comment by Tueno** [comment]
@Ahmedshubber Which TableView's delegate method do you call `startAnimating()`?
If you have called it on `cellForRowAtIndexPath()`, try to move it to `didDisplayCell()`.

**Comment by Ahmedshubber** [comment]
I did that and there's nothing there

**Comment by Ahmedshubber** [comment]
Could I send you the project or could we skype for five min so I could show
it to you

**Comment by jackpaster** [comment]
@Tueno what do you think

**Comment by Tueno** [comment]
@Ahmedshubber 
I'm sorry, but I don't have time for skype. And I can't respond to each use case perfectly.
I think, you should ask it to other community like a stackoverflow or try to customize code yourself.
